
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package itcm;

/** CUP generated interface containing symbol constants. */
public interface syn {
  /* terminals */
  public static final int NUMERO = 39;
  public static final int POW = 9;
  public static final int D_PAR = 6;
  public static final int CONCAT = 14;
  public static final int IN_RANGO = 16;
  public static final int INPUT = 37;
  public static final int DIFERENTE = 27;
  public static final int FORIF = 31;
  public static final int FOR = 32;
  public static final int D_LLAVE = 4;
  public static final int I_LLAVE = 3;
  public static final int IDENTIFICADOR = 40;
  public static final int NOT = 20;
  public static final int AND = 19;
  public static final int IGUAL = 29;
  public static final int FUN = 34;
  public static final int TIPODEDATO = 30;
  public static final int OR = 21;
  public static final int INC = 17;
  public static final int DIV = 12;
  public static final int IF = 33;
  public static final int RETORNO = 28;
  public static final int IDENTICO = 26;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int error = 1;
  public static final int MUL = 8;
  public static final int COMA = 7;
  public static final int MENOR = 22;
  public static final int MOD = 13;
  public static final int ERROR = 42;
  public static final int IMPORT = 36;
  public static final int MAYOR = 23;
  public static final int I_PAR = 5;
  public static final int ELSE = 43;
  public static final int MAYOR_IGUAL = 25;
  public static final int P_COMA = 2;
  public static final int SUM = 10;
  public static final int EX_RANGO = 15;
  public static final int TEXTO = 41;
  public static final int DEC = 18;
  public static final int MENOR_IGUAL = 24;
  public static final int SUB = 11;
  public static final int PRINT = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "P_COMA",
  "I_LLAVE",
  "D_LLAVE",
  "I_PAR",
  "D_PAR",
  "COMA",
  "MUL",
  "POW",
  "SUM",
  "SUB",
  "DIV",
  "MOD",
  "CONCAT",
  "EX_RANGO",
  "IN_RANGO",
  "INC",
  "DEC",
  "AND",
  "NOT",
  "OR",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IDENTICO",
  "DIFERENTE",
  "RETORNO",
  "IGUAL",
  "TIPODEDATO",
  "FORIF",
  "FOR",
  "IF",
  "FUN",
  "RETURN",
  "IMPORT",
  "INPUT",
  "PRINT",
  "NUMERO",
  "IDENTIFICADOR",
  "TEXTO",
  "ERROR",
  "ELSE"
  };
}

