
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package itcm;

/** CUP generated interface containing symbol constants. */
public interface syn {
  /* terminals */
  public static final int OPER_RELACIONAL = 4;
  public static final int ID = 3;
  public static final int TIPO_DE_DATO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO_DE_DATO",
  "ID",
  "OPER_RELACIONAL"
  };
}

