
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package itcm;

/** CUP generated interface containing symbol constants. */
public interface syn {
  /* terminals */
  public static final int ESTRUCTURAS_CONTROL = 11;
  public static final int OPERADOR_RELACIONAL = 8;
  public static final int DECIMAL = 15;
  public static final int FUNCIONES = 12;
  public static final int OPERADOR_CONCATENACION = 4;
  public static final int ERROR = 19;
  public static final int OPERADOR_RANGO = 5;
  public static final int LIBRERIA = 13;
  public static final int OPERADOR_INCREMENTO = 6;
  public static final int TIPODEDATO = 10;
  public static final int EOF = 0;
  public static final int ENTRADAS_SALIDAS = 14;
  public static final int OPERADOR_ARITMETICO = 3;
  public static final int TEXTO = 18;
  public static final int error = 1;
  public static final int NUMERO = 16;
  public static final int OPERADOR_LOGICO = 7;
  public static final int IDENTIFICADOR = 17;
  public static final int DELIMITADOR = 2;
  public static final int OPERADOR_GENERAL = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DELIMITADOR",
  "OPERADOR_ARITMETICO",
  "OPERADOR_CONCATENACION",
  "OPERADOR_RANGO",
  "OPERADOR_INCREMENTO",
  "OPERADOR_LOGICO",
  "OPERADOR_RELACIONAL",
  "OPERADOR_GENERAL",
  "TIPODEDATO",
  "ESTRUCTURAS_CONTROL",
  "FUNCIONES",
  "LIBRERIA",
  "ENTRADAS_SALIDAS",
  "DECIMAL",
  "NUMERO",
  "IDENTIFICADOR",
  "TEXTO",
  "ERROR"
  };
}

